language: python
python:
  - "2.7"
node_js:
  - "0.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev
  - make node_deps
install:
  - pip install -r requirements.txt
script:
  - ( while true; do echo keep alive!; sleep 60; done ) &
  - make travis_test
after_success:
  - coveralls
