sudo: false
language: python
python:
  - "2.7"
  - "3.4"
node_js:
  - "0.12"
before_install:
  - make node_deps
addons:
  apt:
    packages:
      - libevent-dev
install:
  - pip install --user -r requirements.txt
script:
  - ( while true; do echo keep alive!; sleep 60; done ) &
  - make travis_test
after_success:
  - coveralls
